import { CloudSun, MoonStar, SunMedium, Trees, Waves, Zap } from "lucide-react";

export const formThemes = [
  {
    value: "forest_cinematic",
    label: "Forest Cinematic",
    description: "Moss, glass, and soft canopy light.",
    icon: Trees,
    accent: "emerald",
    pageClass: "bg-[#07140d] text-white",
    sceneClass: "forest-scene",
    overlayClass: "bg-[linear-gradient(180deg,rgba(0,0,0,0.08),rgba(3,8,6,0.68))]",
    panelClass: "border-emerald-200/16 bg-[#0b1d14]/86 text-emerald-50",
    choiceClass: "border-white/10 bg-black/18 hover:border-emerald-300/40",
    selectedChoiceClass: "border-emerald-300/70 bg-emerald-300/18",
    buttonClass: "bg-emerald-300 text-emerald-950 hover:bg-emerald-200",
  },
  {
    value: "ocean_flow",
    label: "Ocean Flow",
    description: "Deep water surfaces with clear cyan focus.",
    icon: Waves,
    accent: "sky",
    pageClass: "bg-[#041521] text-white",
    sceneClass: "ocean-scene",
    overlayClass: "bg-[linear-gradient(180deg,rgba(0,0,0,0.08),rgba(4,21,33,0.68))]",
    panelClass: "border-sky-200/16 bg-[#082033]/86 text-sky-50",
    choiceClass: "border-white/10 bg-black/18 hover:border-sky-300/40",
    selectedChoiceClass: "border-sky-300/70 bg-sky-300/18",
    buttonClass: "bg-sky-300 text-sky-950 hover:bg-sky-200",
  },
  {
    value: "cosmic_dark",
    label: "Cosmic Dark",
    description: "Night-sky depth with violet highlights.",
    icon: MoonStar,
    accent: "violet",
    pageClass: "bg-[#060712] text-white",
    sceneClass: "cosmic-scene",
    overlayClass: "bg-[linear-gradient(180deg,rgba(0,0,0,0.08),rgba(6,7,18,0.72))]",
    panelClass: "border-violet-200/16 bg-[#111126]/86 text-violet-50",
    choiceClass: "border-white/10 bg-black/18 hover:border-violet-300/40",
    selectedChoiceClass: "border-violet-300/70 bg-violet-300/18",
    buttonClass: "bg-violet-300 text-violet-950 hover:bg-violet-200",
  },
  {
    value: "minimal_luxury",
    label: "Minimal Luxury",
    description: "Bright editorial surfaces and polished contrast.",
    icon: SunMedium,
    accent: "zinc",
    pageClass: "bg-[#f8fafc] text-zinc-950",
    sceneClass: "luxury-scene",
    overlayClass: "bg-[linear-gradient(180deg,rgba(255,255,255,0.42),rgba(248,250,252,0.82))]",
    panelClass: "border-zinc-200 bg-white/92 text-zinc-950 shadow-zinc-950/10",
    choiceClass: "border-zinc-200 bg-zinc-50 text-zinc-900 hover:border-zinc-400 hover:bg-white",
    selectedChoiceClass: "border-zinc-950 bg-zinc-950 text-white",
    buttonClass: "bg-zinc-950 text-white hover:bg-zinc-800",
  },
  {
    value: "cyber_neon",
    label: "Cyber Neon",
    description: "Cyan glow, dark grid, and energetic controls.",
    icon: Zap,
    accent: "cyan",
    pageClass: "bg-[#040310] text-white",
    sceneClass: "cyber-scene",
    overlayClass: "bg-[linear-gradient(180deg,rgba(0,0,0,0.1),rgba(4,3,16,0.72))]",
    panelClass: "border-cyan-200/18 bg-[#08091a]/88 text-cyan-50",
    choiceClass: "border-white/10 bg-black/18 hover:border-cyan-300/40",
    selectedChoiceClass: "border-cyan-300/70 bg-cyan-300/18",
    buttonClass: "bg-cyan-300 text-cyan-950 hover:bg-cyan-200",
  },
  {
    value: "sunset_studio",
    label: "Sunset Studio",
    description: "Warm editorial gradients with rose accents.",
    icon: CloudSun,
    accent: "rose",
    pageClass: "bg-[#1b0e14] text-white",
    sceneClass: "sunset-scene",
    overlayClass: "bg-[linear-gradient(180deg,rgba(0,0,0,0.08),rgba(27,14,20,0.68))]",
    panelClass: "border-rose-200/16 bg-[#27121a]/86 text-rose-50",
    choiceClass: "border-white/10 bg-black/18 hover:border-rose-300/40",
    selectedChoiceClass: "border-rose-300/70 bg-rose-300/18",
    buttonClass: "bg-rose-300 text-rose-950 hover:bg-rose-200",
  },
] as const;

export type FormThemeValue = (typeof formThemes)[number]["value"];

export function getFormTheme(value?: string | null) {
  return formThemes.find((theme) => theme.value === value) ?? formThemes[0];
}
